backend:
  name: git-gateway
  branch: main
media_folder: 'public/images/uploads'
collections:
  - label: Page
    name: pages
    files:
      - label: About Page
        name: about
        file: 'src/cms/about.json'
        extension: json
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Artist Bio, name: bio, widget: string }
          - label: Exhibitions
            name: exhibitions
            widget: list
            add_to_top: true
            field: { label: item, name: item, widget: string }
          - label: Performances
            name: performances
            widget: list
            add_to_top: true
            field: { label: item, name: item, widget: string }
          - label: Awards
            name: awards
            widget: list
            add_to_top: true
            field: { label: item, name: item, widget: string }
  - label: Blog
    name: blog
    folder: 'src/cms/blog'
    create: true
    extension: json
    slug: '{{slug}}'
    identifier_field: label
    fields:
      - {
          label: 'Layout',
          name: 'layout',
          widget: 'hidden',
          default: 'district',
        }
      - { label: 'Label', name: 'label', widget: 'string' }
      - { label: 'value', name: 'value', widget: 'string' }
      - { label: 'Icon', name: 'icon', widget: 'image' }
