backend:
  name: git-gateway
  branch: main
media_folder: 'public/images/uploads'
public_folder: '/images/uploads'
collections:
  - label: Page
    name: pages
    files:
      - label: Home Page
        name: home
        file: 'public/cms/home.json'
        extension: json
        fields:
          - label: Work/Performances
            name: works
            widget: list
            add_to_top: true
            summary: '{{fields.description}}'
            fields:
              - { label: Image, name: image, widget: image }
              - { label: Description, name: description, widget: text }
              - { label: url, name: url, widget: string, required: false }
      - label: About Page
        name: about
        file: 'public/cms/about.json'
        extension: json
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Artist Bio, name: bio, widget: text }
          - label: Exhibitions
            name: exhibitions
            widget: list
            add_to_top: true
            summary: '{{fields.item}}'
            field: { label: item, name: item, widget: string }
          - label: Performances
            name: performances
            widget: list
            add_to_top: true
            summary: '{{fields.item}}'
            field: { label: item, name: item, widget: string }
          - label: Awards
            name: awards
            widget: list
            add_to_top: true
            summary: '{{fields.item}}'
            field: { label: item, name: item, widget: string }
  - label: Performance
    name: performance
    folder: 'public/cms/performance'
    create: true
    extension: json
    slug: '{{slug}}'
    identifier_field: name
    fields:
      - { label: 'Slug', name: 'slug', widget: 'string' } # for url
      - { label: 'Name', name: 'name', widget: 'string' } # preview display
      - { label: 'Year', name: 'year', widget: 'string' } # preview display
      - { label: 'Preview', name: 'preview', widget: 'image' } # listing page image
      - {
          # details page content
          label: 'DetailsHtml',
          name: 'detailsHtml',
          widget: 'code',
          default_language: 'html',
          output_code_only: true,
        }
  - label: Work
    name: work
    folder: 'public/cms/work'
    create: true
    extension: json
    slug: '{{slug}}'
    identifier_field: name
    fields:
      - { label: 'Slug', name: 'slug', widget: 'string' } # for url
      - { label: 'Name', name: 'name', widget: 'string' } # preview display
      - { label: 'Year', name: 'year', widget: 'string' } # preview display
      - { label: 'Preview', name: 'preview', widget: 'image' } # listing page image
      - {
          # details page content
          label: 'DetailsHtml',
          name: 'detailsHtml',
          widget: 'code',
          default_language: 'html',
          output_code_only: true,
        }
