backend:
  name: git-gateway
  branch: main
media_folder: 'public/images/uploads'
collections:
  - label: Page
    name: pages
    files:
      - label: About Page
        name: about
        file: 'public/cms/about.json'
        extension: json
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Artist Bio, name: bio, widget: text }
          - label: Exhibitions
            name: exhibitions
            widget: list
            add_to_top: true
            summary: '{{fields.item}}'
            field: { label: item, name: item, widget: string }
          - label: Performances
            name: performances
            widget: list
            add_to_top: true
            summary: '{{fields.item}}'
            field: { label: item, name: item, widget: string }
          - label: Awards
            name: awards
            widget: list
            add_to_top: true
            summary: '{{fields.item}}'
            field: { label: item, name: item, widget: string }
  - label: Performance
    name: performance
    folder: 'public/cms/performance'
    create: true
    extension: json
    slug: '{{slug}}'
    identifier_field: name
    fields:
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Year', name: 'year', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Preview', name: 'preview', widget: 'image' }
      - {
          label: 'DetailsHtml',
          name: 'detailsHtml',
          widget: 'code',
          default_language: 'html',
          output_code_only: true,
        }
