backend:
  name: git-gateway
  branch: main
media_folder: 'public/images/uploads'
collections:
  - name: blog
    label: Blog
    folder: 'src/cms/blog'
    create: true
    extension: json
    slug: '{{slug}}'
    identifier_field: label
    fields:
      - {
          label: 'Layout',
          name: 'layout',
          widget: 'hidden',
          default: 'district',
        }
      - { label: 'Label', name: 'label', widget: 'string' }
      - { label: 'value', name: 'value', widget: 'string' }
      - { label: 'Icon', name: 'icon', widget: 'image' }
